### PR TITLE
fix(KONFLUX-14943): auto-fetch all TaskRun pages for PipelineRun details

### PR DESCRIPTION
**Pull request by manosnoam**
## Fixes
Fixes: https://redhat.atlassian.net/browse/KONFLUX-14943

## Description
PipelineRun details can mark the first pipeline task as Idle with empty Details/Results/Logs on completed runs that have more than 30 TaskRuns (e.g. olminstall smoke+bvt). TaskRuns are loaded from Tekton Results / KubeArchive with page_size=30, newest first, so the oldest task falls off page 1 and the UI treats it as missing.

This change auto-fetches remaining TaskRun pages in `useTaskRunsForPipelineRuns` (same pattern as `useScanResults`) and reports `allPagesLoaded=false` until every page is loaded.

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Before the fix - Task content and log are empty:
image

---

image

### After the fix - Task content and log are shown:
image

---

image

## How to test or reproduce?
- Open a completed PipelineRun with 31+ TaskRuns (e.g. olminstall smoke+bvt on stone-prod-p02).
- Confirm the first task (e.g. `parse-pipeline-tests`) shows Succeeded, not Idle, with Details/Results/Logs populated.
- Run `yarn test -- src/hooks/__tests__/useTaskRunsV2.spec.ts` — includes multi-page fetch test.

## Browser conformance:
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved task run pagination so all available pages are fetched automatically.
  * Task run results now remain in a loading state until every page has finished loading.
  * Ensured results include task runs from additional pages once pagination is complete.

* **Tests**
  * Added coverage verifying multi-page task run loading and completion behavior.

### CODE REVIEW

File: src/hooks/useTaskRunsV2.ts [hunk 1]
```diff
@@ -254,9 +255,24 @@ export const useTaskRunsForPipelineRuns = (
     },
   );
 
+  React.useEffect(() => {
+    if (nextPageProps.hasNextPage && !nextPageProps.isFetchingNextPage && loaded && !error) {
```
Comment (rrosatti) [inline src/hooks/useTaskRunsV2.ts:259]: I checked the usage of the `useTaskRunsForPipelineRuns` hook and overall fetching next pages seem like a beneficial addition to have. 

There are only two places in which they were handling the " nextpage fetching logic" by themselves: `src/hooks/usePipelineRunTestOutputResult.ts` and `src/hooks/useScanResults.ts`, which could be updated to stop doing it. 

cc: @sahil143

File: src/hooks/useTaskRunsV2.ts [hunk 2]
```diff
@@ -254,9 +255,24 @@ export const useTaskRunsForPipelineRuns = (
...
+  }, [
+    nextPageProps.hasNextPage,
+    nextPageProps.isFetchingNextPage,
+    loaded,
+    getNextPage,
+    error,
+  ]);
+
+  const allPagesLoaded =
+    loaded && !error && !nextPageProps.isFetchingNextPage && !nextPageProps.hasNextPage;
```
Comment (rrosatti) [inline src/hooks/useTaskRunsV2.ts:271]: Fullsend suggestion is valid here: it would be better to remove the `!error` from the "allPagesLoaded computation"

File: src/hooks/useTaskRunsV2.ts (hunk 1 above)
Comment (sahil143) [reply src/hooks/useTaskRunsV2.ts:259]: if the same hook is being used in the `src/hooks/usePipelineRunTestOutputResult.ts` and `src/hooks/useScanResults.ts` then they should be updated as well.

File: src/hooks/useTaskRunsV2.ts [hunk 3]
```diff
@@ -254,9 +255,24 @@ export const useTaskRunsForPipelineRuns = (
...
+    }
+  }, [
+    nextPageProps.hasNextPage,
+    nextPageProps.isFetchingNextPage,
+    loaded,
+    getNextPage,
+    error,
+  ]);
+
+  const allPagesLoaded =
```
[the remark this answers is not in the document]
Comment (sahil143) [reply src/hooks/useTaskRunsV2.ts:270]: This is a valid suggestion

**Review by sahil143 — CHANGES_REQUESTED** [review]

**Comment by manosnoam** [comment]
I fixed suggestions and rebased, it works great.

Without the patch, we cannot see a few days old tasks' logs.

See this plr for example `rhoai-tenant/applications/rhoai-fbc-fragment-ocp-420/pipelineruns/e2e-cli-nmanos-rh-nightly-pm-rhoai-smoke-czshr`:


image


**With the patch we can see the task's details and logs:**

image

**Comment by manosnoam** [comment]
@coderabbitai review

**Comment by manosnoam** [comment]
@coderabbitai full review

File: src/hooks/useTaskRunsV2.ts (hunk 2 above)
Comment (manosnoam) [reply src/hooks/useTaskRunsV2.ts]: Fixed: loaded && !isFetchingNextPage && (!!error || !hasNextPage)

File: src/hooks/useTaskRunsV2.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/hooks/useTaskRunsV2.ts:327]: Addressed in 259b2fa: `allPagesLoaded` now treats a pagination error as finished loading so consumers can exit the spinner and show the error:

```ts
loaded && !nextPageProps.isFetchingNextPage && (!!error || !nextPageProps.hasNextPage)
```

Added `should report loaded when pagination fails with an error` to cover this path.

File: src/hooks/__tests__/useTaskRunsV2.spec.ts [hunk 4]
```diff
@@ -882,6 +882,66 @@ describe('useTaskRunsV2', () => {
       const callArgs = useK8sWatchResourceMock.mock.calls[0][0];
       expect(callArgs.selector.matchLabels).not.toHaveProperty('tekton.dev/pipelineTask');
     });
+
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/hooks/__tests__/useTaskRunsV2.spec.ts:1041]: Added `should report loaded when pagination fails with an error` in `useTaskRunsV2.spec.ts` (259b2fa). It asserts `allPagesLoaded` is true, the error is propagated, partial page-1 results are kept, and `getNextPage` is not called.

File: src/hooks/useTaskRunsV2.ts (hunk 1 above)
Comment (manosnoam) [reply src/hooks/useTaskRunsV2.ts]: Done in 259b2fa: removed the redundant auto-fetch `useEffect` blocks from `useScanResults.ts` and `usePipelineRunTestOutputResult.ts` now that `useTaskRunsForPipelineRuns` handles pagination. Also simplified their loading guards accordingly.

File: src/shared/components/virtualized-log-viewer/VirtualizedLogContent.tsx [hunk 5]
```diff
@@ -269,7 +269,7 @@ export const VirtualizedLogContent: React.FC<VirtualizedLogContentProps> = ({
   const scrollContainerRef = React.useCallback(
     (node: HTMLDivElement | null) => {
       scrollRef.current = node;
-      navRef(node);
+      (navRef as React.MutableRefObject<HTMLDivElement | null>).current = node;
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/shared/components/virtualized-log-viewer/VirtualizedLogContent.tsx]: Fixed in 259b2fa: `useHotkeys` v5 returns a `RefObject`, not a callback ref. `VirtualizedLogContent` now assigns `navRef.current` in the merged ref callback (same pattern as before #1108). This fixes the `navRef is not a function` crash on the PipelineRun logs tab.

File: src/shared/components/virtualized-log-viewer/useKeyboardNavigation.ts [hunk 6]
```diff
@@ -13,7 +13,7 @@ export const useKeyboardNavigation = ({
   scrollElementRef,
   lineHeight = DEFAULT_LINE_HEIGHT,
   enabled = true,
-}: UseKeyboardNavigationParams): RefCallback<HTMLDivElement | null> => {
+}: UseKeyboardNavigationParams): RefObject<HTMLDivElement | null> => {
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/shared/components/virtualized-log-viewer/useKeyboardNavigation.ts]: Agreed this is outside KONFLUX-14943, but it fixes a regression from main after rebasing: the #1108 migration called `navRef(node)` while `useHotkeys` v5 actually returns a `RefObject`, which crashed the logs tab locally. Kept the fix minimal (3 files) rather than opening a separate PR.

File: src/hooks/useTaskRunsV2.ts [hunk 7]
```diff
@@ -292,9 +294,24 @@ export const useTaskRunsForPipelineRuns = (
     },
   );
 
+  React.useEffect(() => {
+    if (nextPageProps.hasNextPage && !nextPageProps.isFetchingNextPage && loaded && !error) {
+      getNextPage?.();
+    }
+  }, [
+    nextPageProps.hasNextPage,
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/hooks/useTaskRunsV2.ts:320]: Updated in 259b2fa: the effect now checks `getNextPage` is truthy before calling `getNextPage()` (no optional chaining on the call).

File: src/hooks/__tests__/useTaskRunsV2.spec.ts [hunk 8]
```diff
@@ -986,6 +986,101 @@ describe('useTaskRunsV2', () => {
...
+    it('should fetch all TaskRun pages before reporting loaded', async () => {
+      const mockGetNextPage = jest.fn();
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/hooks/__tests__/useTaskRunsV2.spec.ts:1043]: Added `should keep allPagesLoaded false while fetching the next page` in 259b2fa.

File: src/shared/components/virtualized-log-viewer/VirtualizedLogContent.tsx (hunk 5 above)
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/shared/components/virtualized-log-viewer/VirtualizedLogContent.tsx]: Fixed in 7ee22a5: added `assignReactRef()` in `useKeyboardNavigation.ts` so we support both callback refs and ref objects. `useHotkeys` types as `RefCallback` in CI, but at runtime the value is not callable (the #1108 `navRef(node)` path crashed on the logs tab). `VirtualizedLogContent` and the keyboard-nav tests now call `assignReactRef(navRef, node)` instead of casting to `MutableRefObject`. Added unit tests for `assignReactRef`. Verified keyboard navigation on the PipelineRun logs tab locally against stone-prod-p02.

File: src/hooks/__tests__/useTaskRunsV2.spec.ts [hunk 9]
```diff
@@ -101,13 +101,12 @@ const mockTaskRun3: TaskRunKind = {
 describe('useTaskRunsV2', () => {
   let queryClient: QueryClient;
 
-  const renderHookWithQueryClient = (
+  const renderUseTaskRunsV2Hook = (
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/hooks/__tests__/useTaskRunsV2.spec.ts]: Addressed in 7ee22a5: aliased the shared import as `renderHookWithQueryClientUtil` and kept the local helper named `renderHookWithQueryClient`, matching the pattern used in other test files.

File: src/shared/components/virtualized-log-viewer/useKeyboardNavigation.ts [hunk 10]
```diff
@@ -13,7 +13,7 @@ export const useKeyboardNavigation = ({
   scrollElementRef,
   lineHeight = DEFAULT_LINE_HEIGHT,
   enabled = true,
-}: UseKeyboardNavigationParams): RefCallback<HTMLDivElement | null> => {
+}: UseKeyboardNavigationParams) => {
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/shared/components/virtualized-log-viewer/useKeyboardNavigation.ts]: Agreed on the ideal split. Kept it in this PR because it is a blocking regression after rebasing onto main: the #1108 migration called `navRef(node)` but `useHotkeys` v5 does not return a callable ref at runtime (`navRef is not a function` on the logs tab). Local verify on stone-prod-p02 confirmed the fix is required for this branch to pass lint and work in the UI.

File: src/unit-test-utils/mock-react-query.ts [hunk 11]
```diff
@@ -25,3 +25,17 @@ export function renderWithQueryClient(
...
+
+export function renderHookWithQueryClient<TResult, TProps>(
+  hook: (props: TProps) => TResult,
+  options?: RenderHookOptions<TProps> & { client?: QueryClient },
+) {
+  const { client, ...hookOptions } = options ?? {};
+  const queryClient = client ?? createTestQueryClient();
+
+  function Wrapper({ children }: { children: React.ReactNode }) {
+    return React.createElement(QueryClientProvider, { client: queryClient }, children);
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/unit-test-utils/mock-react-query.ts:37]: Addressed in 7ee22a5: `renderHookWithQueryClient` now takes `Omit<RenderHookOptions<TProps>, 'wrapper'> & { client?: QueryClient }`, consistent with `renderWithQueryClient` in the same file.

File: src/hooks/__tests__/useTaskRunsV2.spec.ts [hunk 12]
```diff
@@ -986,6 +978,112 @@ describe('useTaskRunsV2', () => {
       const callArgs = useK8sWatchResourceMock.mock.calls[0][0];
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/hooks/__tests__/useTaskRunsV2.spec.ts:1038]: Thanks — agreed those three cases (multi-page load, pagination error, and `isFetchingNextPage`) are the important ones for centralizing pagination in `useTaskRunsForPipelineRuns`.

File: src/hooks/useTaskRunsV2.ts [hunk 13]
```diff
@@ -292,9 +294,30 @@ export const useTaskRunsForPipelineRuns = (
     },
   );
 
+  React.useEffect(() => {
+    if (
+      nextPageProps.hasNextPage &&
+      !nextPageProps.isFetchingNextPage &&
+      loaded &&
+      !error &&
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/hooks/useTaskRunsV2.ts]: Fixed: `useTaskRunsV2` now exposes `historicalError` (Tekton Results or KubeArchive error only). `useTaskRunsForPipelineRuns` uses `historicalError` for the auto-fetch guard and `allPagesLoaded`, while the merged `error` still includes `clusterError` for consumers. Added `should continue historical pagination when the cluster watch fails` in `useTaskRunsV2.spec.ts`.

File: src/hooks/useTaskRunsV2.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/hooks/useTaskRunsV2.ts:327]: Follow-up in `d41703c7`: `allPagesLoaded` and the auto-fetch guard now use `historicalError` (Tekton Results / KubeArchive only), not the merged `error` that includes `clusterError`. Pagination errors still stop loading; cluster-watch failures no longer block remaining historical pages. Merged `error` is unchanged for consumers.

File: src/shared/components/virtualized-log-viewer/VirtualizedLogContent.tsx (hunk 5 above)
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/shared/components/virtualized-log-viewer/VirtualizedLogContent.tsx]: Latest push `d41703c7` includes this fix (`assignReactRef`) plus the `historicalError` pagination guard. Lint and unit tests pass locally.

**Comment by manosnoam** [comment]
@sahil143 @rrosatti Latest push `d41703c7` addresses the remaining review items:

- `historicalError` separates Tekton Results / KubeArchive pagination errors from merged `clusterError`, so historical pages keep loading after a cluster-watch failure (CodeRabbit)
- `assignReactRef` for `useHotkeys` v5 ref handling (fullsend high)
- Test helper naming + `Omit<wrapper>` on `renderHookWithQueryClient`

CI is running. Ready for another look when you have a moment.

File: src/hooks/useTaskRunsV2.ts [hunk 14]
```diff
@@ -206,6 +206,16 @@ export const useTaskRunsV2 = (
       return clusterError || kubearchiveQuery.error;
     })();
 
+    const historicalError = (() => {
```
Comment (rrosatti) [inline src/hooks/useTaskRunsV2.ts:210]: hmm, do we really need this? can't we use the `error` that's already returned by this hook? 🤔

File: src/shared/components/virtualized-log-viewer/useKeyboardNavigation.ts [hunk 15]
```diff
@@ -1,8 +1,18 @@
-import type { RefCallback, RefObject } from 'react';
+import type { MutableRefObject, Ref, RefObject } from 'react';
 import { useHotkeys } from 'react-hotkeys-hook';
 
 const DEFAULT_LINE_HEIGHT = 20;
 
+/** Attach a node to a React ref whether it is a callback ref or a ref object. */
+export const assignReactRef = <T>(ref: Ref<T> | undefined, value: T | null): void => {
```
Comment (rrosatti) [inline src/shared/components/virtualized-log-viewer/useKeyboardNavigation.ts]: hmm, can you tell us why this change was needed? It doesn't look like it's connected with the main PR's changes 👀

File: src/hooks/useTaskRunsV2.ts (hunk 14 above)
Comment (manosnoam) [reply src/hooks/useTaskRunsV2.ts:210]: Good question — we still return the merged `error` from this hook (`clusterError || tektonError` / `clusterError || kubearchiveQuery.error`) for consumers to display.

`historicalError` is only for pagination control inside `useTaskRunsForPipelineRuns`. The merged `error` includes `clusterError`, and we intentionally start Tekton Results / KubeArchive when the cluster watch fails (`needsMoreData` is true on `clusterError`). If the auto-fetch guard and `allPagesLoaded` used merged `error`, a cluster-watch failure would stop `getNextPage()` and mark all pages loaded while `hasNextPage` is still true — leaving TaskRuns truncated. CodeRabbit flagged this exact case.

So: consumers keep merged `error`; pagination uses historical-query error only. Happy to rename or inline if you prefer, but we need the two concepts separated somewhere.

File: src/shared/components/virtualized-log-viewer/useKeyboardNavigation.ts (hunk 15 above)
Comment (manosnoam) [reply src/shared/components/virtualized-log-viewer/useKeyboardNavigation.ts]: Agreed it is outside KONFLUX-14943 — it landed here because rebasing onto main surfaced a blocking regression from #1108.

That migration called `navRef(node)` on the return value of `useHotkeys`, but `react-hotkeys-hook` v5 does not give you a callable ref at runtime (`navRef is not a function` on the PipelineRun logs tab). Casting to `MutableRefObject` and setting `.current` also failed CI type-checking (`TS2352`).

`assignReactRef` is a small helper that works whether `useHotkeys` returns a callback ref or a ref object (types vs runtime disagree). `VirtualizedLogContent` merges it into the scroll container ref callback. Verified on stone-prod-p02 locally.

I can split it into a follow-up PR if you prefer, but it blocked lint + logs-tab keyboard nav on this branch.

File: src/hooks/__tests__/useTaskRunsV2.spec.ts [hunk 16]
```diff
@@ -986,6 +981,143 @@ describe('useTaskRunsV2', () => {
...
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/hooks/__tests__/useTaskRunsV2.spec.ts:1038]: Fixed

File: src/hooks/__tests__/useTaskRunsV2.spec.ts [hunk 17]
```diff
@@ -9,10 +9,13 @@ import {
 } from '~/kubearchive/hooks';
 import { WatchK8sResource } from '~/types/k8s';
 import { TaskRunKind } from '~/types/task-run';
+import {
+  createTestQueryClient,
+  renderHookWithQueryClient as renderHookWithQueryClientUtil,
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/hooks/__tests__/useTaskRunsV2.spec.ts]: Fixed

File: src/hooks/__tests__/useTaskRunsV2.spec.ts [hunk 18]
```diff
@@ -9,10 +9,13 @@ import {
 } from '~/kubearchive/hooks';
 import { WatchK8sResource } from '~/types/k8s';
 import { TaskRunKind } from '~/types/task-run';
+import {
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/hooks/__tests__/useTaskRunsV2.spec.ts]: Fixed

**Comment by manosnoam** [comment]
> * **`src/hooks/useTaskRunsV2.ts`** (file-level): _Line 267_ · **[medium]** api-breaking-change
> 
> 
> useTaskRunsForPipelineRuns changes the meaning of its second return value from 'loaded' (true after first page loads) to 'allPagesLoaded' (true only after all pages are fetched). Production consumers that destructure only [taskRuns, loaded, error] — including ComponentLatestBuild.tsx, PipelineRunDetailsTab.tsx, PipelineRunLogsTab.tsx, BuildLogViewer.tsx, and useConformaResult.tsx — will now receive 'false' during pagination instead of 'true', causing them to show loading state longer for PipelineRuns with >30 TaskRuns. This is likely the intended behavior but worth confirming.
> 
> **Suggested fix:** Review all call sites that destructure the second return value. Verify that the extended loading state is acceptable UX for all affected views, or consider exposing both 'loaded' and 'allPagesLoaded' separately.

Verified all call sites that destructure the second return value (PipelineRunDetailsTab, PipelineRunLogsTab, TaskRunListView, BuildLogViewer, ComponentLatestBuild, build/integration side panels, useConformaResult, useScanResults, usePipelineRunTestOutputResult). Each gates rendering or derived data on it and needs the full TaskRun set — partial first-page data caused incorrect visualization for large pipeline runs. The longer spinner during pagination is intentional; we’re not exposing a separate first-page loaded flag. JSDoc updated to document allPagesLoaded semantics.

File: src/shared/components/virtualized-log-viewer/useKeyboardNavigation.ts [hunk 19]
```diff
@@ -1,4 +1,4 @@
-import type { RefCallback, RefObject } from 'react';
+import type { Ref, RefObject } from 'react';
```
Comment (rrosatti) [inline src/shared/components/virtualized-log-viewer/useKeyboardNavigation.ts]: I'd suggest to undo this change. And if it's some error/bug that you found, could you please create a ticket for it? 🙏

File: src/shared/components/virtualized-log-viewer/VirtualizedLogContent.tsx [hunk 20]
```diff
@@ -269,7 +270,7 @@ export const VirtualizedLogContent: React.FC<VirtualizedLogContentProps> = ({
   const scrollContainerRef = React.useCallback(
     (node: HTMLDivElement | null) => {
       scrollRef.current = node;
-      navRef(node);
+      assignReactRef(navRef, node);
```
Comment (rrosatti) [inline src/shared/components/virtualized-log-viewer/VirtualizedLogContent.tsx]: ditto

File: src/shared/utils/assign-react-ref.ts [hunk 21]
```diff
@@ -0,0 +1,11 @@
+import type { MutableRefObject, Ref } from 'react';
+
+/** Attach a node to a React ref whether it is a callback ref or a ref object. */
+export const assignReactRef = <T>(ref: Ref<T> | undefined, value: T | null): void => {
```
Comment (rrosatti) [inline src/shared/utils/assign-react-ref.ts]: ditto

File: src/hooks/useTaskRunsV2.ts [hunk 22]
```diff
@@ -21,6 +21,8 @@ export type TaskRunWatchMeta = {
   dataUpdatedAt: number;
   isFetching: boolean;
   refetch: () => Promise<unknown>;
+  /** Tekton Results or KubeArchive error only; excludes cluster-watch failures. */
+  historicalError: unknown;
```
Comment (rrosatti) [inline src/hooks/useTaskRunsV2.ts]: hmm, I believe the `historicalError` field should not be part of `TaskRunWatchMeta` type 🤔

File: src/hooks/useTaskRunsV2.ts (hunk 1 above)
Comment (manosnoam) [reply src/hooks/useTaskRunsV2.ts]: Still addressed in `f0ec77b`: removed redundant auto-fetch `useEffect`s from `useScanResults.ts` and `usePipelineRunTestOutputResult.ts`; tests updated.

File: src/hooks/useTaskRunsV2.ts (hunk 2 above)
Comment (manosnoam) [reply src/hooks/useTaskRunsV2.ts]: Updated in `f0ec77b` — `allPagesLoaded` now uses `historicalError` (7th tuple element), not merged `error`:

```ts
loaded && !nextPageProps.isFetchingNextPage && (!!historicalError || !nextPageProps.hasNextPage)
```

So pagination errors stop fetching without treating cluster-watch failures as historical pagination failures.

File: src/shared/components/virtualized-log-viewer/VirtualizedLogContent.tsx (hunk 5 above)
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/shared/components/virtualized-log-viewer/VirtualizedLogContent.tsx]: Follow-up in `f0ec77b`: reverted — log-viewer files are no longer part of this PR. I could not reproduce `navRef is not a function` locally on current main with `react-hotkeys-hook@5.3.3` (returns a `RefCallback`, so `navRef(node)` is valid). Will open a separate ticket/PR if we see it elsewhere.

File: src/shared/components/virtualized-log-viewer/useKeyboardNavigation.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/shared/components/virtualized-log-viewer/useKeyboardNavigation.ts]: Reverted in `f0ec77b` — out of scope for this PR. Same as above: no crash reproduced locally with `react-hotkeys-hook@5.3.3`.

File: src/hooks/useTaskRunsV2.ts (hunk 14 above)
Comment (manosnoam) [reply src/hooks/useTaskRunsV2.ts:210]: Follow-up in `f0ec77b`: removed `historicalError` from `TaskRunWatchMeta`; it is now the **7th return value** of `useTaskRunsV2`. Only `useTaskRunsForPipelineRuns` uses it for pagination control. Merged `error` for consumers is unchanged.

File: src/shared/components/virtualized-log-viewer/useKeyboardNavigation.ts (hunk 15 above)
Comment (manosnoam) [reply src/shared/components/virtualized-log-viewer/useKeyboardNavigation.ts]: Reverted in `f0ec77b` per feedback — not needed for this PR. I couldn't reproduce the logs-tab crash locally with `react-hotkeys-hook@5.3.3`.

File: src/hooks/__tests__/useTaskRunsV2.spec.ts [hunk 23]
```diff
@@ -986,6 +981,157 @@ describe('useTaskRunsV2', () => {
       const callArgs = useK8sWatchResourceMock.mock.calls[0][0];
       expect(callArgs.selector.matchLabels).not.toHaveProperty('tekton.dev/pipelineTask');
     });
+
+    it('should fetch all TaskRun pages before reporting loaded', async () => {
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/hooks/__tests__/useTaskRunsV2.spec.ts:1042]: Added in `f0ec77b`:
- `should fetch all KubeArchive pages before reporting loaded`
- `should report loaded when KubeArchive pagination fails with an error`
- `should not auto-fetch pages when the hook is disabled` (`null`, `null`)

File: src/hooks/useTaskRunsV2.ts [hunk 24]
```diff
@@ -292,9 +308,32 @@ export const useTaskRunsForPipelineRuns = (
     },
   );
 
+  React.useEffect(() => {
+    if (
+      nextPageProps.hasNextPage &&
+      !nextPageProps.isFetchingNextPage &&
+      loaded &&
+      !historicalError &&
+      getNextPage
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/hooks/useTaskRunsV2.ts:315]: Confirmed intentional in `f0ec77b`. Reviewed consumers that destructure `[taskRuns, loaded, error]` — all gate rendering on `loaded` and need the full TaskRun set. Longer spinner during pagination is expected vs showing partial data.

File: src/hooks/useTaskRunsV2.ts [hunk 25]
```diff
@@ -292,9 +308,32 @@ export const useTaskRunsForPipelineRuns = (
     },
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/hooks/useTaskRunsV2.ts:306]: Acknowledged — `fetchNextPage` from React Query is stable; no change needed.

File: src/hooks/useTaskRunsV2.ts [hunk 26]
```diff
@@ -21,6 +21,8 @@ export type TaskRunWatchMeta = {
   dataUpdatedAt: number;
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/hooks/useTaskRunsV2.ts:21]: Fixed in `f0ec77b`: updated `useTaskRunsV2` JSDoc for the 7-tuple return shape. `historicalError` is no longer on `TaskRunWatchMeta` — it is the 7th tuple element.

File: src/hooks/useTaskRunsV2.ts [hunk 27]
```diff
@@ -262,7 +275,10 @@ export const useTaskRunsV2 = (
  * @param pipelineRunName - Name of the pipeline run to fetch TaskRuns for
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/hooks/useTaskRunsV2.ts:273]: Agreed — intentional core fix for this PR; JSDoc on `useTaskRunsForPipelineRuns` documents `allPagesLoaded` semantics.

File: src/hooks/__tests__/useTaskRunsV2.spec.ts [hunk 28]
```diff
@@ -460,9 +494,13 @@ describe('useTaskRunsV2', () => {
...
 
-      const { result } = renderHookWithQueryClient('default', {
-        selector: { matchLabels: { 'tekton.dev/pipelineRun': 'test-pr' } },
-      });
+      const { result } = renderHookWithQueryClient(
+        () =>
+          useTaskRunsV2('default', {
+            selector: { matchLabels: { 'tekton.dev/pipelineRun': 'test-pr' } },
+          }),
+        { client: queryClient },
```
[the remark this answers is not in the document]
Comment (manosnoam) [reply src/hooks/__tests__/useTaskRunsV2.spec.ts:502]: Agreed — hook tests cover `allPagesLoaded`; consumer test suites own UI gating.

File: src/shared/components/virtualized-log-viewer/useKeyboardNavigation.ts (hunk 19 above)
Comment (manosnoam) [reply src/shared/components/virtualized-log-viewer/useKeyboardNavigation.ts]: Done in `f0ec77b` — reverted. Could not reproduce the crash locally with `react-hotkeys-hook@5.3.3`. Happy to file a follow-up if we see it in another environment.

File: src/shared/components/virtualized-log-viewer/VirtualizedLogContent.tsx (hunk 20 above)
Comment (manosnoam) [reply src/shared/components/virtualized-log-viewer/VirtualizedLogContent.tsx]: Reverted in `f0ec77b` — no longer part of this PR.

File: src/shared/utils/assign-react-ref.ts (hunk 21 above)
Comment (manosnoam) [reply src/shared/utils/assign-react-ref.ts]: Removed in `f0ec77b` — `assign-react-ref.ts` is not in this PR anymore.

File: src/hooks/useTaskRunsV2.ts (hunk 22 above)
Comment (manosnoam) [reply src/hooks/useTaskRunsV2.ts]: Agreed — removed from `TaskRunWatchMeta` in `f0ec77b`. `historicalError` is now the 7th return value of `useTaskRunsV2`; only `useTaskRunsForPipelineRuns` consumes it.

**Comment by manosnoam** [comment]
Thanks @rrosatti  @sahil143 , I addressed your latest feedback:

- log-viewer changes reverted
- historicalError moved off TaskRunWatchMeta
- KubeArchive + disabled-hook tests added
- docs/JSDoc updated. 

I verified locally on stone-prod-p02. Ready for another look.

**Review by rrosatti — APPROVED** [review]
LGTM, thanks for the fix!! :)

**Review by marcin-michal — APPROVED** [review]
LGTM, tested and works as expected

**Review by sahil143 — APPROVED** [review]
